import { ServerModel } from "../server.model";

export const getDefaultServer = (customUrl?: string) => {
  const url = customUrl || window?.location?.origin || "http://localhost:3000";

  return new ServerModel(url, "Default server, generated by swagman");
};
